/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/low_poly_80s_sports_car/scene.gltf --types -t -k -o app/components/Car.tsx 
Author: ville.eriksen (https://sketchfab.com/ville.eriksen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-80s-sports-car-eaf8991e95604532803a954c3fd3d5cb
Title: Low Poly 80's Sports Car
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Car_BaseColor_0: THREE.Mesh
    Car_Emission_0: THREE.Mesh
  }
  materials: {
    BaseColor: THREE.MeshStandardMaterial
    Emission: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/low_poly_80s_sports_car/scene.gltf') as unknown as GLTFResult
  const texture = useTexture(
    '/models/low_poly_80s_sports_car/textures/BaseColor_diffuse.png',
    (tex) => {
      tex.flipY = false
      tex.colorSpace = THREE.SRGBColorSpace
      tex.needsUpdate = true
    },
  )

  return (
    <group {...props} dispose={null}>
      <group name="Car" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh name="Car_BaseColor_0" geometry={nodes.Car_BaseColor_0.geometry} material={materials.BaseColor} material-map={texture} material-needsUpdate />
        <mesh name="Car_Emission_0" geometry={nodes.Car_Emission_0.geometry} material={materials.Emission} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_80s_sports_car/scene.gltf')
